name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Dotnet Publish
      run: dotnet publish -o deploy
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/Mu3eenApi/Mu3eenApi/deploy/
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
       command: sudo service mu3eenApi restart
       host: ${{ secrets.REMOTE_HOST }}
       username: ${{ secrets.REMOTE_USER }}
       password: ${{ secrets.REMOTE_PASSWORD }}
    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -c Mu3eenContext -p Mu3eenApi -s Mu3eenContext
      env:
       ASPNETCORE_ENVIRONMENT: Production
